# Generated by Django 2.2.2 on 2019-06-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MUN', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formnew',
            old_name='subject',
            new_name='Committee',
        ),
        migrations.RemoveField(
            model_name='formnew',
            name='body',
        ),
    ]
