# Generated by Django 2.2.2 on 2019-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN', '0003_remove_formnew_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='formnew',
            name='number',
            field=models.CharField(default='0123456789', max_length=15),
        ),
    ]
