# Generated by Django 2.2.2 on 2019-06-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN', '0004_formnew_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='formnew',
            name='committee',
            field=models.CharField(choices=[('C1', 'Committee1'), ('C2', 'Committee2'), ('IP', 'InternationalPress')], default='C1', max_length=20),
        ),
    ]
