# Generated by Django 2.2.2 on 2019-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN', '0005_formnew_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='formnew',
            name='Past_Experience',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='formnew',
            name='college',
            field=models.CharField(default='NITD', max_length=200),
        ),
        migrations.AlterField(
            model_name='formnew',
            name='committee',
            field=models.CharField(choices=[('C1', 'United Nations General Assembly - DISEC'), ('C2', 'The All India Oppostion Meet'), ('IPJ', 'International Press Journalist'), ('IPP', 'International Press Photographer')], default='C1', max_length=20),
        ),
    ]
