# Generated by Django 2.2.2 on 2019-07-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN', '0006_auto_20190624_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(default='0123456789', max_length=15)),
                ('committee', models.CharField(choices=[('C1', 'United Nations General Assembly - DISEC'), ('C2', 'The All India Oppostion Meet')], default='C1', max_length=20)),
                ('college', models.CharField(default='NITD', max_length=200)),
                ('Past_Experience', models.CharField(default='None', max_length=1000)),
                ('preference1', models.CharField(default='None', max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='FormNew',
        ),
    ]
