# Generated by Django 2.2.2 on 2019-07-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MUN', '0007_auto_20190701_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeenew',
            name='preference1',
        ),
    ]
