# Generated by Django 2.2.2 on 2019-07-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN', '0009_committeenew_preference1'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeenew',
            name='preference2',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='committeenew',
            name='preference3',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
