# Generated by Django 2.2.2 on 2019-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUN', '0010_auto_20190701_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(default='0123456789', max_length=15)),
                ('committee', models.CharField(choices=[('IPJ', 'International Press Journalist'), ('IPP', 'International Press Photographer')], default='IPJ', max_length=20)),
                ('college', models.CharField(default='NITD', max_length=200)),
                ('Past_Experience', models.CharField(default='None', max_length=1000)),
                ('preference1', models.CharField(default='None', max_length=150)),
                ('preference2', models.CharField(default='None', max_length=150)),
                ('preference3', models.CharField(default='None', max_length=150)),
            ],
        ),
    ]
