# Generated by Django 2.2.2 on 2019-07-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MUN', '0011_ipnew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipnew',
            old_name='committee',
            new_name='Choice',
        ),
    ]
